//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GothicCheckers.GUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleHelpStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleHelpStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GothicCheckers.GUI.Localization.ConsoleHelpStrings", typeof(ConsoleHelpStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move a piece from pos1 to pos2. Positions must be in standard format, i.e. A1, B5 etc. Example: move A2 A3. Supply additional positions to perform a jump move. Example: move A2 A4 C6..
        /// </summary>
        public static string Help_CommandDetail_Move {
            get {
                return ResourceManager.GetString("Help_CommandDetail_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a new game with specified settings. Game modes are h2h h2pc pc2pc (h for human). Difficulties are e (for easy), n (for normal) and h (for hard). Colors are w and b (applies only to h2pc game, where color specifies the color of human player. Examples:.
        /// </summary>
        public static string Help_CommandDetail_NewGame {
            get {
                return ResourceManager.GetString("Help_CommandDetail_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newgame h2pc n b - starts new human vs computer game with normal difficulty and human as black player.
        /// </summary>
        public static string Help_CommandDetail_NewGame_Example1 {
            get {
                return ResourceManager.GetString("Help_CommandDetail_NewGame_Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newgame pc2pc h e - starts new computer vs computer game with one hard and one easy computer players.
        /// </summary>
        public static string Help_CommandDetail_NewGame_Example2 {
            get {
                return ResourceManager.GetString("Help_CommandDetail_NewGame_Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command List:.
        /// </summary>
        public static string Help_CommandList {
            get {
                return ResourceManager.GetString("Help_CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatically print game board after move command..
        /// </summary>
        public static string Help_CommandList_AutoPrint {
            get {
                return ResourceManager.GetString("Help_CommandList_AutoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type help command (e.g. help move) for detailed help with a specific command..
        /// </summary>
        public static string Help_CommandList_MoreHelp {
            get {
                return ResourceManager.GetString("Help_CommandList_MoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves a piece.
        /// </summary>
        public static string Help_CommandList_Move {
            get {
                return ResourceManager.GetString("Help_CommandList_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts a new game.
        /// </summary>
        public static string Help_CommandList_NewGame {
            get {
                return ResourceManager.GetString("Help_CommandList_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Help {
            get {
                return ResourceManager.GetString("Help_Help", resourceCulture);
            }
        }
    }
}
