//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GothicCheckers.GUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GothicCheckers.GUI.Localization.MainWindowStrings", typeof(MainWindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Game.
        /// </summary>
        public static string Button_ContinueGame {
            get {
                return ResourceManager.GetString("Button_ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Game.
        /// </summary>
        public static string Button_PauseGame {
            get {
                return ResourceManager.GetString("Button_PauseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move History.
        /// </summary>
        public static string GroupBox_MoveHistory {
            get {
                return ResourceManager.GetString("GroupBox_MoveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Game.
        /// </summary>
        public static string GroupBox_ReplayGame {
            get {
                return ResourceManager.GetString("GroupBox_ReplayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings....
        /// </summary>
        public static string MainMenu_Edit_GameSettings {
            get {
                return ResourceManager.GetString("MainMenu_Edit_GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainMenu_Edit_Language {
            get {
                return ResourceManager.GetString("MainMenu_Edit_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string MainMenu_Edit_Language_Czech {
            get {
                return ResourceManager.GetString("MainMenu_Edit_Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MainMenu_Edit_Language_English {
            get {
                return ResourceManager.GetString("MainMenu_Edit_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Move.
        /// </summary>
        public static string MainMenu_Edit_RedoMove {
            get {
                return ResourceManager.GetString("MainMenu_Edit_RedoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Debug Console Window.
        /// </summary>
        public static string MainMenu_Edit_ShowDebugConsole {
            get {
                return ResourceManager.GetString("MainMenu_Edit_ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Players.
        /// </summary>
        public static string MainMenu_Edit_SwitchPlayers {
            get {
                return ResourceManager.GetString("MainMenu_Edit_SwitchPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Move.
        /// </summary>
        public static string MainMenu_Edit_UndoMove {
            get {
                return ResourceManager.GetString("MainMenu_Edit_UndoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Game.
        /// </summary>
        public static string MainMenu_Game {
            get {
                return ResourceManager.GetString("MainMenu_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainMenu_Game_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Game_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Game....
        /// </summary>
        public static string MainMenu_Game_LoadGame {
            get {
                return ResourceManager.GetString("MainMenu_Game_LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Game....
        /// </summary>
        public static string MainMenu_Game_NewGame {
            get {
                return ResourceManager.GetString("MainMenu_Game_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Game As....
        /// </summary>
        public static string MainMenu_Game_SaveGameAs {
            get {
                return ResourceManager.GetString("MainMenu_Game_SaveGameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MainMenu_Help_About {
            get {
                return ResourceManager.GetString("MainMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainMenu_Help_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Move....
        /// </summary>
        public static string MainMenu_Help_SuggestMove {
            get {
                return ResourceManager.GetString("MainMenu_Help_SuggestMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic Checkers.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
    }
}
